name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# 同一分支只保留最新一次執行，避免重複跑
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10 (with pip cache)
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}   # 讓 pytest 能 import app/*
          TOKENIZERS_PARALLELISM: "false"
        run: pytest -q

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t ai-short-video-mvp:ci .
